name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.mvn_install.outputs.build_status }}
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies
      id: mvn_install
      run: |
        mvn install -DskipTests
        echo "build_status=$?" >> $GITHUB_OUTPUT
      continue-on-error: true
      
    - name: Run tests
      run: mvn test

    - name: Package application
      run: mvn package

  fakeDeploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Print Build Status
        run: | 
          echo "Build Status: ${{ needs.build.outputs.build_status }}"

      - name: Deploy
        if: ${{ needs.build.outputs.build_status }}
        run: echo Deploy Successful

      - name: Destroy Artifacts
        if: ${{ needs.build.outputs.build_status != 0}}
        run: echo Artifacts Destroyed

  snyk:
    uses: ./.github/workflows/snyk.yml
    needs: build
