name: Snyk
on: [workflow_call]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: "79f64122-7e0f-45a6-a68b-4b8ff369d73d"
